<?php

namespace App\Console\Commands;

use App\Models\Category;
use App\Models\RssFeed;
use App\Models\Site;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

class ImportCampaigns extends Command
{
    protected $signature = 'wp:import-campaigns
        {--site= : MediaChief site ID to import into}
        {--file= : Path to JSON export file from mediachief-export.php}
        {--ai : Enable AI rewriting on imported campaigns}
        {--images : Enable Pixabay image fetching on imported campaigns}
        {--auto-publish : Auto-publish articles from these campaigns}
        {--dry-run : Show what would be imported without making changes}';

    protected $description = 'Import RSS feed campaigns from a WordPress export JSON file (generated by mediachief-export.php)';

    public function handle(): int
    {
        $siteId = $this->option('site');
        $filePath = $this->option('file');
        $dryRun = $this->option('dry-run');

        // Interactive mode
        if (! $siteId) {
            $sites = Site::where('is_active', true)->get();

            if ($sites->isEmpty()) {
                $this->error('No active sites found. Create a site first.');

                return self::FAILURE;
            }

            $siteName = $this->choice(
                'Which site to import into?',
                $sites->pluck('name', 'id')->toArray()
            );

            $siteId = $sites->firstWhere('name', $siteName)?->id;
        }

        if (! $filePath) {
            $filePath = $this->ask('Path to JSON export file');
        }

        $site = Site::find($siteId);

        if (! $site) {
            $this->error("Site #{$siteId} not found.");

            return self::FAILURE;
        }

        if (! file_exists($filePath)) {
            $this->error("File not found: {$filePath}");

            return self::FAILURE;
        }

        $json = file_get_contents($filePath);
        $data = json_decode($json, true);

        if (! $data || ! isset($data['campaigns'])) {
            $this->error('Invalid JSON format. Expected output from mediachief-export.php');

            return self::FAILURE;
        }

        $this->info("Export from: {$data['site_url']} ({$data['site_name']})");
        $this->info("Exported at: {$data['exported_at']}");
        $this->info("Campaigns: {$data['summary']['total_campaigns']}");
        $this->info("Categories: {$data['summary']['total_categories']}");
        $this->info("Sources: " . implode(', ', $data['summary']['sources_found']));
        $this->newLine();

        if ($dryRun) {
            $this->warn('[DRY RUN] No changes will be made.');
            $this->newLine();
        }

        // Step 1: Import categories
        $categoryMap = $this->importCategories($site, $data['categories'] ?? [], $dryRun);

        // Step 2: Import campaigns as RssFeed records
        $this->importCampaigns($site, $data['campaigns'], $categoryMap, $dryRun);

        $this->newLine();
        $this->info('Done!');

        return self::SUCCESS;
    }

    /**
     * Import WP categories and return a wp_id -> local_id map.
     */
    private function importCategories(Site $site, array $wpCategories, bool $dryRun): array
    {
        if (empty($wpCategories)) {
            return [];
        }

        $this->info('Importing categories...');
        $map = [];
        $created = 0;
        $existing = 0;

        // Build parent mapping for hierarchy
        $parentMap = [];
        foreach ($wpCategories as $cat) {
            if (! empty($cat['parent_id'])) {
                $parentMap[$cat['id']] = $cat['parent_id'];
            }
        }

        foreach ($wpCategories as $cat) {
            $slug = Str::slug($cat['slug'] ?: $cat['name']);

            $localCat = Category::where('site_id', $site->id)
                ->where('slug', $slug)
                ->first();

            if ($localCat) {
                $map[$cat['id']] = $localCat->id;
                $existing++;

                continue;
            }

            if ($dryRun) {
                $this->line("  [DRY] Would create category: {$cat['name']} ({$slug})");
                $created++;

                continue;
            }

            // Resolve parent if exists
            $parentId = null;
            if (! empty($cat['parent_id']) && isset($map[$cat['parent_id']])) {
                $parentId = $map[$cat['parent_id']];
            }

            $localCat = Category::create([
                'site_id' => $site->id,
                'parent_id' => $parentId,
                'name' => $cat['name'],
                'slug' => $slug,
                'description' => $cat['description'] ?? null,
                'is_active' => true,
                'sort_order' => 0,
            ]);

            $map[$cat['id']] = $localCat->id;
            $created++;
        }

        $this->info("Categories: {$created} created, {$existing} already existed");

        return $map;
    }

    /**
     * Import campaigns as RssFeed records.
     */
    private function importCampaigns(Site $site, array $campaigns, array $categoryMap, bool $dryRun): void
    {
        $this->info('Importing campaigns...');
        $this->newLine();

        $aiEnabled = $this->option('ai');
        $imagesEnabled = $this->option('images');
        $autoPublish = $this->option('auto-publish');

        $created = 0;
        $skipped = 0;
        $inactive = 0;

        foreach ($campaigns as $campaign) {
            $url = $campaign['url'] ?? '';

            if (empty($url)) {
                continue;
            }

            // Check if this feed URL already exists for this site
            $exists = RssFeed::where('site_id', $site->id)
                ->where('url', $url)
                ->exists();

            if ($exists) {
                $this->line("  <comment>[SKIP]</comment> {$campaign['name']} - already exists");
                $skipped++;

                continue;
            }

            // Map WP category ID to local category ID
            $categoryId = null;
            $wpCatId = $campaign['category_wp_id'] ?? null;
            if ($wpCatId && isset($categoryMap[$wpCatId])) {
                $categoryId = $categoryMap[$wpCatId];
            }

            // Determine fetch interval (Google News = faster)
            $fetchInterval = (int) ($campaign['fetch_interval'] ?? 30);
            $isGoogleNews = str_contains($url, 'news.google.com') || str_contains($url, 'google.com/rss');
            if ($isGoogleNews && $fetchInterval > 15) {
                $fetchInterval = 15;
            }

            $isActive = $campaign['is_active'] ?? true;

            if ($dryRun) {
                $status = $isActive ? 'ACTIVE' : 'PAUSED';
                $source = $campaign['source'] ?? 'unknown';
                $this->line("  [DRY] [{$status}] [{$source}] {$campaign['name']} -> {$url}");
                $created++;

                continue;
            }

            RssFeed::create([
                'site_id' => $site->id,
                'category_id' => $categoryId,
                'name' => $campaign['name'] ?? 'Imported Campaign',
                'url' => $url,
                'source_name' => $campaign['source_name'] ?? parse_url($url, PHP_URL_HOST),
                'fetch_interval' => $fetchInterval,
                'is_active' => $isActive,
                'auto_publish' => $autoPublish || ($campaign['auto_publish'] ?? true),
                'ai_rewrite' => $aiEnabled,
                'ai_language' => $site->language ?? 'en',
                'fetch_images' => $imagesEnabled,
            ]);

            $statusLabel = $isActive ? '<info>[NEW]</info>' : '<comment>[NEW/PAUSED]</comment>';
            $this->line("  {$statusLabel} {$campaign['name']} -> {$url}");

            if ($isActive) {
                $created++;
            } else {
                $inactive++;
                $created++;
            }
        }

        $this->newLine();
        $this->info("Campaigns: {$created} created ({$inactive} paused), {$skipped} skipped (duplicates)");

        if ($aiEnabled) {
            $this->info('AI rewriting: ENABLED on all imported campaigns');
        }
        if ($imagesEnabled) {
            $this->info('Pixabay images: ENABLED on all imported campaigns');
        }
    }
}
